version: '3.2'

services:
  im:
    build:
      context: ./
      dockerfile: docker-swoole
    restart: always
    ports:
      - 9501:9501
      - 9502:9502
    volumes:
       - .:/var/www


  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
       - dbdata2:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080

  redis:
    image: redis:5.0.6-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata: {}
  dbdata2: {}
  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret


